- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Install ZSH
      become: true
      apt: name=zsh

    - name: Change shell to zsh
      become: true
      shell: chsh -s $(which zsh)

    - name: Check that the somefile.conf exists
      stat:
        path: /home/mm/.oh-my-zsh
      register: oh_my_stats

    - name: Oh-My-Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: oh_my_stats.stat.exists == False
      become_user: mm

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
